/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'niels' at '5/11/16 2:15 PM' with Gradle 2.9
 *
 * @author niels, @date 5/11/16 2:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
